/** Fixed machine readable error codes; never rely on free text alone. */
export const PrepressErrorCode = {
  INVALID_PDF: "INVALID_PDF",
  PAGE_COUNT_INVALID: "PAGE_COUNT_INVALID",
  PAGE_SIZE_MISMATCH: "PAGE_SIZE_MISMATCH",
  TEMPLATE_UNKNOWN: "TEMPLATE_UNKNOWN",
  MASTER_UNAVAILABLE: "MASTER_UNAVAILABLE",
  MASTER_INVALID_PDF: "MASTER_INVALID_PDF",
  MASTER_LAYER_MISSING: "MASTER_LAYER_MISSING",
  MASTER_LAYER_ORDER_INVALID: "MASTER_LAYER_ORDER_INVALID",
  MASTER_LAYER_VISIBILITY_INVALID: "MASTER_LAYER_VISIBILITY_INVALID",
  MASTER_WHITE_SEPARATION_MISSING: "MASTER_WHITE_SEPARATION_MISSING",
  MASTER_WHITE_OVERPRINT_MISSING: "MASTER_WHITE_OVERPRINT_MISSING",
  MASTER_ARTWORK_BLOCK_MISSING: "MASTER_ARTWORK_BLOCK_MISSING",
  ILLUSTRATOR_PRIVATE_DATA_PRESENT: "ILLUSTRATOR_PRIVATE_DATA_PRESENT",
  OUTPUT_INVALID_PDF: "OUTPUT_INVALID_PDF",
  OUTPUT_PAGE_COUNT_INVALID: "OUTPUT_PAGE_COUNT_INVALID",
  OUTPUT_PAGE_SIZE_MISMATCH: "OUTPUT_PAGE_SIZE_MISMATCH",
  OUTPUT_LAYER_MISSING: "OUTPUT_LAYER_MISSING",
  OUTPUT_LAYER_ORDER_INVALID: "OUTPUT_LAYER_ORDER_INVALID",
  OUTPUT_LAYER_VISIBILITY_INVALID: "OUTPUT_LAYER_VISIBILITY_INVALID",
  OUTPUT_WHITE_SEPARATION_MISSING: "OUTPUT_WHITE_SEPARATION_MISSING",
  OUTPUT_WHITE_OVERPRINT_MISSING: "OUTPUT_WHITE_OVERPRINT_MISSING",
  OUTPUT_ARTWORK_MISSING: "OUTPUT_ARTWORK_MISSING",
  OUTPUT_ARTWORK_OCG_UNLINKED: "OUTPUT_ARTWORK_OCG_UNLINKED",
  OUTPUT_ARTWORK_SCALED: "OUTPUT_ARTWORK_SCALED",
  OUTPUT_MASTER_CONTENT_CHANGED: "OUTPUT_MASTER_CONTENT_CHANGED",
  OUTPUT_EXTRA_OCG: "OUTPUT_EXTRA_OCG",
  TECHNICAL_FAIL: "TECHNICAL_FAIL",
} as const;

export type PrepressErrorCodeValue =
  (typeof PrepressErrorCode)[keyof typeof PrepressErrorCode];

export class PrepressFailure extends Error {
  constructor(
    public readonly code: PrepressErrorCodeValue,
    message: string,
  ) {
    super(message);
    this.name = "PrepressFailure";
  }
}